@baseUrl = http://127.0.0.1:7001


###

GET  {{baseUrl}}

####


###
POST {{baseUrl}}/api/user
Content-Type: application/json

{
  "name": "zpk",
  "phone": "18612875765",
  "typeId": 28,
  "tagsId": [54, 55]
}
###

####
GET {{baseUrl}}/api/user
####

###
POST {{baseUrl}}/api/user/del
Content-Type: application/json

{
  "Id": 10
}
###
###
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "name": "test2",
  "phone": "18612875765"
}


###


####
GET {{baseUrl}}/api/user/register
####




###
POST {{baseUrl}}/api/info
Content-Type: application/json

{
  "name": "name",
  "show": true
}
###
###
GET  {{baseUrl}}/api/info
###
###
POST {{baseUrl}}/api/info/del
Content-Type: application/json

{
  "id": 0
}
###





###
POST {{baseUrl}}/api/type
Content-Type: application/json

{
  "name": "JAVA",
  "tags": [{
    "name": "test4"
  }]
}
###
###
GET  {{baseUrl}}/api/type
###
###
POST {{baseUrl}}/api/type/del/31
Content-Type: application/json

{
  "id": 0
}
###





###
POST {{baseUrl}}/api/tag
Content-Type: application/json

{
  "type": "JAVA",
  "name": "html"
}
###
###
GET  {{baseUrl}}/api/tag
###
###
POST {{baseUrl}}/api/tag/del/67
Content-Type: application/json

{
  "id": 0
}
###
