@baseUrl = http://127.0.0.1:7001


###

GET  {{baseUrl}}

####


####
GET {{baseUrl}}/api/user/register
####


###
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "name": "test",
  "phone": "18612875765",
  "typeId": 46,
  "tagsId": []
}
###

####
GET {{baseUrl}}/api/user
####

###
POST {{baseUrl}}/api/user/del
Content-Type: application/json

{
  "Id": 0
}
###
###
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "name": "test2",
  "phone": "18612875765"
}


###






###
POST {{baseUrl}}/api/info
Content-Type: application/json

{
  "name": "name",
  "show": true
}
###
###
GET  {{baseUrl}}/api/info
###
###
POST {{baseUrl}}/api/info/del
Content-Type: application/json

{
  "id": 0
}
###





###
POST {{baseUrl}}/api/type
Content-Type: application/json

{
  "name": "PHP",
  "tags": [{
    "name": "html"
  }]
}
###
###
GET  {{baseUrl}}/api/type
###
###
POST {{baseUrl}}/api/type/del
Content-Type: application/json

{
  "id": 0
}
###





###
POST {{baseUrl}}/api/tag
Content-Type: application/json

{
  "id": "28",
  "name": "3"
}
###
###
GET  {{baseUrl}}/api/tag
###
###
POST {{baseUrl}}/api/tag/del
Content-Type: application/json

{
  "Id": 0
}
###
